package jp.co.arthur.db.entity;

import java.io.Serializable;
import java.util.Date;

import jp.co.arthur.common.log.annotation.Ignore;
import jp.co.arthur.common.log.annotation.Mask;

public class LoginUser implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.LOGIN_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.PASSWORD
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	@Mask
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.VALID_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Date validDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login_user.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	@Ignore
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.LOGIN_ID
	 * @return  the value of login_user.LOGIN_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.LOGIN_ID
	 * @param loginId  the value for login_user.LOGIN_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.PASSWORD
	 * @return  the value of login_user.PASSWORD
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.PASSWORD
	 * @param password  the value for login_user.PASSWORD
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.ACCOUNT
	 * @return  the value of login_user.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.ACCOUNT
	 * @param account  the value for login_user.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.VALID_DATE
	 * @return  the value of login_user.VALID_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Date getValidDate() {
		return validDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.VALID_DATE
	 * @param validDate  the value for login_user.VALID_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.REG_DATE
	 * @return  the value of login_user.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.REG_DATE
	 * @param regDate  the value for login_user.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login_user.UPDATE_DATE
	 * @return  the value of login_user.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login_user.UPDATE_DATE
	 * @param updateDate  the value for login_user.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}