package jp.co.arthur.db.entity;

import java.io.Serializable;
import java.util.Date;

public class PurchaseInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.PURCHASE_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Integer purchaseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.USER_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Integer userInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.ITEM_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.ITEM_NAME
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.ITEM_UNIT_MONEY
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Integer itemUnitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.ITEM_AMOUNT
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Integer itemAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.REG_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Date regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_info.UPDATE_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.PURCHASE_INFO_ID
     *
     * @return the value of purchase_info.PURCHASE_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Integer getPurchaseInfoId() {
        return purchaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.PURCHASE_INFO_ID
     *
     * @param purchaseInfoId the value for purchase_info.PURCHASE_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setPurchaseInfoId(Integer purchaseInfoId) {
        this.purchaseInfoId = purchaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.USER_INFO_ID
     *
     * @return the value of purchase_info.USER_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.USER_INFO_ID
     *
     * @param userInfoId the value for purchase_info.USER_INFO_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.ITEM_ID
     *
     * @return the value of purchase_info.ITEM_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.ITEM_ID
     *
     * @param itemId the value for purchase_info.ITEM_ID
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.ITEM_NAME
     *
     * @return the value of purchase_info.ITEM_NAME
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.ITEM_NAME
     *
     * @param itemName the value for purchase_info.ITEM_NAME
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.ITEM_UNIT_MONEY
     *
     * @return the value of purchase_info.ITEM_UNIT_MONEY
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Integer getItemUnitMoney() {
        return itemUnitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.ITEM_UNIT_MONEY
     *
     * @param itemUnitMoney the value for purchase_info.ITEM_UNIT_MONEY
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setItemUnitMoney(Integer itemUnitMoney) {
        this.itemUnitMoney = itemUnitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.ITEM_AMOUNT
     *
     * @return the value of purchase_info.ITEM_AMOUNT
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Integer getItemAmount() {
        return itemAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.ITEM_AMOUNT
     *
     * @param itemAmount the value for purchase_info.ITEM_AMOUNT
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setItemAmount(Integer itemAmount) {
        this.itemAmount = itemAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.REG_DATE
     *
     * @return the value of purchase_info.REG_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.REG_DATE
     *
     * @param regDate the value for purchase_info.REG_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_info.UPDATE_DATE
     *
     * @return the value of purchase_info.UPDATE_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_info.UPDATE_DATE
     *
     * @param updateDate the value for purchase_info.UPDATE_DATE
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}