package jp.co.arthur.db.entity;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.USER_INFO_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Integer userInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.USER_INFO_ID
	 * @return  the value of user_info.USER_INFO_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Integer getUserInfoId() {
		return userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.USER_INFO_ID
	 * @param userInfoId  the value for user_info.USER_INFO_ID
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setUserInfoId(Integer userInfoId) {
		this.userInfoId = userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.ACCOUNT
	 * @return  the value of user_info.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.ACCOUNT
	 * @param account  the value for user_info.ACCOUNT
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.REG_DATE
	 * @return  the value of user_info.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.REG_DATE
	 * @param regDate  the value for user_info.REG_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.UPDATE_DATE
	 * @return  the value of user_info.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.UPDATE_DATE
	 * @param updateDate  the value for user_info.UPDATE_DATE
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}