package jp.co.arthur.db.mapper;

import java.util.List;
import jp.co.arthur.db.entity.LoginUser;
import jp.co.arthur.db.entity.LoginUserExample;
import org.apache.ibatis.annotations.Param;

public interface LoginUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	long countByExample(LoginUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int deleteByExample(LoginUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int deleteByPrimaryKey(String loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int insert(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int insertSelective(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	List<LoginUser> selectByExample(LoginUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	LoginUser selectByPrimaryKey(String loginId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByPrimaryKeySelective(LoginUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login_user
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByPrimaryKey(LoginUser record);
}