package jp.co.arthur.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.arthur.db.entity.PrefecturesMt;
import jp.co.arthur.db.entity.PrefecturesMtExample;

public interface PrefecturesMtMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	long countByExample(PrefecturesMtExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int deleteByExample(PrefecturesMtExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int deleteByPrimaryKey(Integer prefecturesId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int insert(PrefecturesMt record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int insertSelective(PrefecturesMt record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	List<PrefecturesMt> selectByExample(PrefecturesMtExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	PrefecturesMt selectByPrimaryKey(Integer prefecturesId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int updateByExampleSelective(@Param("record") PrefecturesMt record, @Param("example") PrefecturesMtExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int updateByExample(@Param("record") PrefecturesMt record, @Param("example") PrefecturesMtExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int updateByPrimaryKeySelective(PrefecturesMt record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table prefectures_mt
	 *
	 * @mbg.generated Sun Oct 14 18:45:27 JST 2018
	 */
	int updateByPrimaryKey(PrefecturesMt record);
}