package jp.co.arthur.db.mapper;

import java.util.List;
import jp.co.arthur.db.entity.PurchaseInfo;
import jp.co.arthur.db.entity.PurchaseInfoExample;
import org.apache.ibatis.annotations.Param;

public interface PurchaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    long countByExample(PurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int deleteByExample(PurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int deleteByPrimaryKey(Integer purchaseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int insert(PurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int insertSelective(PurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    List<PurchaseInfo> selectByExample(PurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    PurchaseInfo selectByPrimaryKey(Integer purchaseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int updateByExampleSelective(@Param("record") PurchaseInfo record, @Param("example") PurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int updateByExample(@Param("record") PurchaseInfo record, @Param("example") PurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int updateByPrimaryKeySelective(PurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_info
     *
     * @mbg.generated Sun Oct 07 01:53:51 JST 2018
     */
    int updateByPrimaryKey(PurchaseInfo record);
}