package jp.co.arthur.db.mapper;

import java.util.List;
import jp.co.arthur.db.entity.UserInfo;
import jp.co.arthur.db.entity.UserInfoExample;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	long countByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int deleteByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int deleteByPrimaryKey(Integer userInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	List<UserInfo> selectByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	UserInfo selectByPrimaryKey(Integer userInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Sun Oct 07 01:53:51 JST 2018
	 */
	int updateByPrimaryKey(UserInfo record);
}